### ISSUE TITLE
Willing to Accept PRs?

### ISSUE THREAD

**Issue by Benny739** [jonaswitt/stripe-datev-exporter#6]
Hi,

thanks for your work, it will save me a lot of time.
Are you willing to accept PRs, to make the tool more generally usable? 
I saw in some places you made the tool tailored to your usecase. You could keep it that way, or we could build some options to e.g. make account numbers configurable.

I think it would be best to put all config options in the env file.

**Comment by jonaswitt** [comment]
Thanks for your feedback! I'm willing to accept PRs, but since I started building this tool I always thought that if somebody wants to use it, they will have to make code-level changes anyway to fit their style of accounting - I have considered this repo to be more like a code template. Other people have [forked it](https://github.com/jonaswitt/stripe-datev-exporter/network) and adjusted it to match their requirements (maintaining the ability to merge upstream changes is considered helpful). I'm not sure if making account numbers configurable alone will do it, and more powerful configuration options might make things a lot more complex. But if you're happy with configurable account numbers, then let's make them configurable.

**Comment by Benny739** [comment]
Thanks for your feedback.
Yeah you are probably right, I'll have a look and see what we have to change to make it fit our usecase.
If I think it makes sense I'll come back to you.

Thanks for your work again!
